### ISSUE TITLE
Handling column not present in data

### ISSUE THREAD

**Issue by ee07dazn** [sanjuthomas/kafka-connect-gcp-bigtable#22]
Hi @sanjuthomas 

Does the transform handle a column that is not present in the map?
Say for example, my config looks like 
```
    families:
    - data
    familyQualifiers:
    - data:
      - anonymousId
      - context
```
And a test data looks like 
```
{
   "anonymousId" : "random123"
}
```
Will the transform you have baked into, will automatically set the context to `null` or throw an error. Guess, I will find out pretty soon but if it throws an error, is there a good way to handle it ?
